-- 1. Delete from the most dependent tables first (those with foreign keys)
DELETE FROM ProductCheckDetails;
DELETE FROM ProductChecks;
DELETE FROM ProductPlacements;
DELETE FROM ProductsInOrder;
DELETE FROM ProductsInStorage;
DELETE FROM Products;
DELETE FROM DeliveryOrders;
DELETE FROM Suppliers;
DELETE FROM Employees;
DELETE FROM Clients;
DELETE FROM Cinemas;
DELETE FROM PaymentMethods;
DELETE FROM ProductTypes;
DELETE FROM DeliveryOrderStatuses;
DELETE FROM MoviesGenres;
DELETE FROM Movies;
DELETE FROM Halls;
DELETE FROM Seats;
DELETE FROM ScreeningFormats;
DELETE FROM Languages;
DELETE FROM Countries;
DELETE FROM AgeRestrictions;
DELETE FROM Genres;
DELETE FROM Runs;
DELETE FROM Screenings;
DELETE FROM Checks;
DELETE FROM Tickets;
DELETE FROM CheckTickets;
DELETE FROM Publishers;
DELETE FROM Cities;
DELETE FROM HallTechnologies;

-- 2. Reset identity columns (only for tables using IDENTITY)
DBCC CHECKIDENT ('ProductCheckDetails', RESEED, 0);
DBCC CHECKIDENT ('ProductChecks', RESEED, 0);
DBCC CHECKIDENT ('ProductPlacements', RESEED, 0);
DBCC CHECKIDENT ('ProductsInOrder', RESEED, 0);
DBCC CHECKIDENT ('ProductsInStorage', RESEED, 0);
DBCC CHECKIDENT ('Products', RESEED, 0);
DBCC CHECKIDENT ('DeliveryOrders', RESEED, 0);
DBCC CHECKIDENT ('Suppliers', RESEED, 0);
DBCC CHECKIDENT ('Employees', RESEED, 0);
DBCC CHECKIDENT ('Clients', RESEED, 0);
DBCC CHECKIDENT ('Cinemas', RESEED, 0);
DBCC CHECKIDENT ('PaymentMethods', RESEED, 0);
DBCC CHECKIDENT ('ProductTypes', RESEED, 0);
DBCC CHECKIDENT ('DeliveryOrderStatuses', RESEED, 0);
DBCC CHECKIDENT ('MoviesGenres', RESEED, 0);
DBCC CHECKIDENT ('Movies', RESEED, 0);
DBCC CHECKIDENT ('Halls', RESEED, 0);
DBCC CHECKIDENT ('Seats', RESEED, 0);
DBCC CHECKIDENT ('ScreeningFormats', RESEED, 0);
DBCC CHECKIDENT ('Languages', RESEED, 0);
DBCC CHECKIDENT ('Countries', RESEED, 0);
DBCC CHECKIDENT ('AgeRestrictions', RESEED, 0);
DBCC CHECKIDENT ('Genres', RESEED, 0);
DBCC CHECKIDENT ('Runs', RESEED, 0);
DBCC CHECKIDENT ('Screenings', RESEED, 0);
DBCC CHECKIDENT ('Checks', RESEED, 0);
DBCC CHECKIDENT ('Tickets', RESEED, 0);
DBCC CHECKIDENT ('CheckTickets', RESEED, 0);
DBCC CHECKIDENT ('Publishers', RESEED, 0);
DBCC CHECKIDENT ('Cities', RESEED, 0);
DBCC CHECKIDENT ('HallTechnologies', RESEED, 0);
